relativeURLs = true
title = "Julian Arteaga"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[params]
shortbio = ""
logo = "Headshot.jpg"

[markup]
  [markup.highlight]
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

