relativeURLs = true
title = "Julián Arteaga"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[params]
shortbio = "Ph.D. Candidate in Agricultural and Resource Economics, UC Davis"
logo = "Headshot.jpg"

[markup]
  [markup.highlight]
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

